version: '3.8'

services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:latest
    ports:
      - '4180:4180'
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Keycloak
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://keycloak.berget.ai/realms/iteam
      # Replace with your Keycloak OAuth credentials
      - OAUTH2_PROXY_CLIENT_ID=demo
      - OAUTH2_PROXY_CLIENT_SECRET=Yh8GYal2qaPE7tFe4Ka0mt6XgpqmLPTS
      # Generate a random string for cookie secret
      - OAUTH2_PROXY_COOKIE_SECRET=a4375069cebd0cd33b7fea46f1fc7c78
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      # No upstream needed when not using as reverse proxy
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_REVERSE_PROXY=false
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_SCOPE=openid email profile
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_SKIP_EMAIL_VERIFICATION=true
      - OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS=true
      - OAUTH2_PROXY_SKIP_AUTH_ROUTES=^/api/
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - oauth2-proxy
    networks:
      - app-network

  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
