version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
