version: '3.8'

services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:latest
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PROVIDER=github
      # Replace with your GitHub OAuth credentials
      - OAUTH2_PROXY_CLIENT_ID=your_github_client_id
      - OAUTH2_PROXY_CLIENT_SECRET=your_github_client_secret
      # Generate a random string for cookie secret
      - OAUTH2_PROXY_COOKIE_SECRET=cookie_secret_value
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://api:3001
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - oauth2-proxy
    networks:
      - app-network

  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
